#!/usr/bin/env Rscript

require_package_version <- function(name, version) {
  if (packageVersion(name) < version) {
    stop(sprintf("Please upgrade to at least %s '%s'", name, version))
  }
}

require_package_version("dust", "0.4.1")
require_package_version("odin.dust", "0.0.8")

odin.dust::odin_dust_package(here::here())
